import os
import telebot
import time
import random
import threading
from emoji import emojize
from telebot import types
from pymongo import MongoClient
import traceback

def createuser():
    return{'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
           'ANONIMUS':'ZDES MOGLA BI BIT VASHA REKLAMA',
          }    

client = MongoClient('there was p0lunins mongo token')
db = client.mags
players = db.players
while True:
    #players.insert_one(createuser())
    print(players)


        
print('7777')
bot.polling(none_stop=True,timeout=600)
